queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}

pull_request_rules:
  - name: backport patches to v6.0.x branch
    conditions:
      - base=main
      - label=backport/6.0.x
    actions:
      backport:
        branches:
          - release/v6.0.x
  - name: backport patches to v5.0.x branch
    conditions:
      - base=main
      - label=backport/5.0.x
    actions:
      backport:
        branches:
          - release/v5.0.x
  - name: backport patches to v4.0.x branch
    conditions:
      - base=main
      - label=backport/4.0.x
    actions:
      backport:
        branches:
          - release/v4.0.x
  - name: backport patches to v3.0.x branch
    conditions:
      - base=main
      - label=backport/3.0.x
    actions:
      backport:
        branches:
          - release/v3.0.x
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
