accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000apoint"]
  - name: bob
    coins: ["5000000000000apoint"]
validator:
  name: alice
  staked: "100000000000000000000apoint"
faucet:
  name: bob
  coins: ["10apoint"]
build:
  binary: "pointd"
init:
  home: "$HOME/.pointd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "point_10711-1"
  app_state:
    staking:
      params:
        bond_denom: "apoint"
    mint:
      params:
        mint_denom: "apoint"
    crisis:
      constant_fee:
        denom: "apoint"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "apoint"
    evm:
      params:
        evm_denom: "apoint"
