accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aevmos"]
  - name: bob
    coins: ["5000000000000aevmos"]
validator:
  name: alice
  staked: "100000000000000000000aevmos"
faucet:
  name: bob 
  coins: ["10aevmos"]
build:
  binary: "evoblockd"
init:
  home: "$HOME/.evoblockd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "evmosd_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "aEVO"
    mint:
      params:
        mint_denom: "aEVO"
    crisis:
      constant_fee:
        denom: "aEVO"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aEVO"
    evm:
      params:
        evm_denom: "aEVO"
