FROM golang:1.22.3-bullseye AS build-env

# checkov:skip=CKV_DOCKER_3:No need to create a user, this is only used on tests
ARG BRANCH_NAME

WORKDIR /go/src/github.com/evmos/

RUN git clone "https://github.com/evmos/evmos.git"

WORKDIR /go/src/github.com/evmos/evmos

RUN git checkout ${BRANCH_NAME}

RUN make build

FROM golang:1.22.3-bullseye

# checkov:skip=CKV_DOCKER_5:No problem if it is cached because targets specific version
RUN apt-get update \ 
&& apt-get install jq=1.6-2.1 -y --no-install-recommends \ 
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/evmos/evmos

COPY ./init-node.sh .

# perms to make init-node.sh executable
RUN chmod +x init-node.sh

COPY --from=build-env /go/src/github.com/evmos/evmos/build/evmosd /usr/bin/evmosd

EXPOSE 26656 26657 1317 9090 8545 8546
HEALTHCHECK CMD curl --fail http://localhost:26657 || exit 1

CMD ["sh", "./init-node.sh"]
