# argument to provide specific version of eidon-chain node
ARG INITIAL_VERSION
# checkov:skip=CKV_DOCKER_3:No need to create a user, this is only used on tests
FROM tharsishq/eidon-chain:$INITIAL_VERSION

WORKDIR /go/src/github.com/Eidon-AI/eidon-chain

COPY ./init-node.sh .

# JSON-RPC server
EXPOSE 8545

HEALTHCHECK CMD curl --fail http://localhost:26657 || exit 1

CMD ["sh", "./init-node.sh"]
