ARG INITIAL_VERSION
FROM golang:1.20.0-bullseye AS build-env

WORKDIR /go/src/github.com/evmos/

RUN git clone "https://github.com/evmos/evmos.git"

WORKDIR /go/src/github.com/evmos/evmos

RUN apt-get update -y
RUN apt-get install git -y

RUN git checkout ${INITIAL_VERSION}

RUN make build

FROM golang:1.20.0-bullseye

RUN apt-get update -y
RUN apt-get install ca-certificates jq -y

WORKDIR /go/src/github.com/evmos/evmos

COPY ./upgrade/upgrade-init.sh .

# perms to make upgrade-init.sh executable
RUN chmod +x upgrade-init.sh

COPY --from=build-env /go/src/github.com/evmos/evmos/build/evmosd /usr/bin/evmosd

EXPOSE 26656 26657 1317 9090 8545 8546

CMD ["sh", "./upgrade-init.sh"]