name: Changelog Diff

on:
  pull_request:
    branches: [main]

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check Changelog for changes
        uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md
